#! /bin/bash
trap '' ERR
echo "Step 2"
touch sample1 sample2
ls -F
echo "Step 3"
ls -l sample1 sample2 sample3
echo "Step 4"
ls -l sample1 sample2 sample3 > file
echo "Step 5"
echo "Type cat file"
read keepGoing 
echo "Step 6"
ls -l sample1 sample2 sample3 2>file
echo "Step 7"
echo "Type cat file"
read keepGoing
echo "Step 8"
echo "ls -l sample1 sample2 sample3 > file 2>file2"
ls -l sample1 sample2 sample3 > file 2>file2
echo "Step 9"
echo "Type cat file"
read keepGoing
echo "Step 10"
echo "Type cat file2"
read keepGoing
echo "Step 11"
echo "ls -l sample1 sample2 sample3 > file 2> &1 will produce error"
echo "Step 12"
echo "Type cat file"
read keepGoing
echo "Step 13"
echo "ls -l sample1 sample2 sample3 > &2 2>file2 will error"
echo "Step 14"
echo "Type cat file2"
read keepGoing
echo "Step 15"
echo "date >> file"
date >> file
echo "Step 16"
echo "Type cat file"
read keepGoing
echo "Step 17"
echo "date >> file"
echo "Step 18"
echo "Type cat file"
read keepGoing
echo "Step 19"
echo "tr o O /etc/hosts"
tr o O /etc/hosts
echo "Step 20"
echo "tr o O </etc/hosts"
tr o O </etc/hosts
tr o O /etc/hosts
